#Practice Questions

# Question 1
Write a function `compute_score(X_train, y_train, X_test, y_test)` to do the following on the `Iris` dataset-

Write your code keeping in mind:
- Split the Iris dataset into train and test set with 70:30 ratio 
- Import svm.SVC as 'model'
- kernel as 'rbf', regularization parameter as 20 and gamma as 'auto'
-Take `random_state=42`.
- Train the model using trining data and predict the computed model's score using test data.

Which of the following options is the computed score?

(a) -1.0

(b) -0.5

(c) 1.0

(d) 0.5


**Option c**


In [ ]:
import numpy as np
from sklearn import svm, datasets
import json
import random
np.random.seed(42)
iris = datasets.load_iris()
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.3)
def COMPUTE_SCORE(X_train, y_train, X_test, y_test):
  model1 = svm.SVC(kernel='rbf',C=20,gamma='auto')
  model1.fit(X_train,y_train)
  score1 = model1.score(X_test, y_test)
  return score1

score1 =COMPUTE_SCORE(X_train, y_train, X_test, y_test)
print(score1)

1.0


#Question 2
In 'Question 1', apply a pipeline containing a `MinMaxScaler()`function called`Scaler` and a `svm.svc()` called `classifier`with the parameters : `kernel='linear', decision_function_shape='ovr', C=1, class_weight=None`. Calculate the precision value and f1 score and mark the correct option from the list below.

(a) 1.0, 1.0

(b) 0.8, 0.8

(c) 0.99, 0.99

(d) 0.97, 0.87

**Option a**


In [ ]:
from sklearn.pipeline import Pipeline
from sklearn import metrics
from sklearn import svm
from sklearn.svm import LinearSVC
from sklearn.preprocessing import StandardScaler, MinMaxScaler
pipe_1 = Pipeline([('scaler', MinMaxScaler()),
                         ("classifier", svm.SVC(kernel='linear', decision_function_shape='ovr', C=1, class_weight=None))])

# Fit the estimator , pipeline

pipe_1.fit(X_train,y_train)

Pipeline(steps=[('scaler', MinMaxScaler()),
                ('classifier', SVC(C=1, kernel='linear'))])

In [ ]:

from sklearn.metrics import precision_score, recall_score, f1_score
y_pred = pipe_1.predict(X_test)
precisionScore = precision_score(y_test, y_pred, average='micro')
recallSscore = recall_score(y_test, y_pred, average='micro')
f1Score = f1_score(y_test, y_pred, average='micro')

print("Precision: {:.2f} ".format(precisionScore))
print("Recall: {:.2f} ".format(recallSscore))
print("f1_Score: {:.2f} ".format(f1Score))

Precision: 1.00 
Recall: 1.00 
f1_Score: 1.00 


#Question 3

Import the `iris` dataset and drop the rows where `class=Iris-versicolor`. Apply a pipeline containing a `MinMaxScaler()`function called`Scaler` and a `svm.svc()` called `classifier`. Split the `iris` dataset into 50:50 ratio with `random_state=0`. Mark the correct recall value from the given options.

(a) 1.00

(b) 0.22

(C) 0.96

(d) 2.33

**Option a**



In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from sklearn import datasets
from pandas.plotting import scatter_matrix

In [ ]:
# Import the libraries for performing classification
from sklearn import svm
from sklearn.svm import LinearSVC
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
from sklearn.metrics import classification_report
from sklearn.metrics import plot_roc_curve
from sklearn.metrics import roc_auc_score
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.pipeline import Pipeline
from sklearn import metrics
from sklearn.metrics import plot_confusion_matrix
from sklearn.model_selection import cross_val_score

In [ ]:
#Define the column names
col_name=["sepal_length_in_cm", "sepal_width_in_cm","petal_length_in_cm","petal_width_in_cm", "class"]

#Read the dataset
df = pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data", header = None, names= col_name)

In [ ]:
data = df
# get names of indexes for which column 'class' has value 'Iris-setosa'
index_names = data[ data["class"] == 'Iris-versicolor' ].index
  
# drop these row indexes
# from dataFrame
data.drop(index_names, inplace = True)
  
data

sepal_length_in_cm  sepal_width_in_cm  ...  petal_width_in_cm           class
0                   5.1                3.5  ...                0.2     Iris-setosa
1                   4.9                3.0  ...                0.2     Iris-setosa
2                   4.7                3.2  ...                0.2     Iris-setosa
3                   4.6                3.1  ...                0.2     Iris-setosa
4                   5.0                3.6  ...                0.2     Iris-setosa
..                  ...                ...  ...                ...             ...
145                 6.7                3.0  ...                2.3  Iris-virginica
146                 6.3                2.5  ...                1.9  Iris-virginica
147                 6.5                3.0  ...                2.0  Iris-virginica
148                 6.2                3.4  ...                2.3  Iris-virginica
149                 5.9                3.0  ...                1.8  Iris-virginica

[100 rows x 5 columns]

In [ ]:
# Separatre the input and output feature values

X = data.iloc[:,:-1]
y = data.iloc[:,-1].values

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.5, random_state = 0)

print('Shape of training data',X_train.shape)
print('Shape of training labels', y_train.shape)
print('Shape of testing data', X_test.shape)
print('Shape of testing labels',y_test.shape)

Shape of training data (50, 4)
Shape of training labels (50,)
Shape of testing data (50, 4)
Shape of testing labels (50,)


In [ ]:
X=np.array(X_train)
y=np.array(y_train)
# Let us consider sepal length and sepal width
X=X[:,(0,1)]
X.shape

(50, 2)

In [ ]:
# Create a pipeline

pipe_2 = Pipeline([('scaler', MinMaxScaler()),
                         ("classifier", svm.SVC(kernel='linear', decision_function_shape='ovr', C=1, class_weight=None))])

# Fit the estimator , pipeline

pipe_2.fit(X_train,y_train)

# Get the predictions

y_pred = pipe_2.predict(X_test)

In [ ]:
from sklearn.metrics import precision_score, recall_score, f1_score

precisionScore = precision_score(y_test, y_pred, average='micro')
recallSscore = recall_score(y_test, y_pred, average='micro')
f1Score = f1_score(y_test, y_pred, average='micro')

print("Precision: {:.2f} ".format(precisionScore))
print("Recall: {:.2f} ".format(recallSscore))
print("f1_Score: {:.2f} ".format(f1Score))

Precision: 1.00 
Recall: 1.00 
f1_Score: 1.00 


#Question 4

Write the function `compute_score(X_train, y_train, X_test, y_test)` to do the following on the `Iris` dataset-

Write your code keeping in mind:
- Split the Iris dataset into train and test set with 70:30 ratio and `random_state=42`.
- Import sklearn.svm.LinearSVC as 'model'
- Consider loss function `loss=hinge`,`random_state=42` and `penalty=l2`.
- Train the 'model' and mark the computed 'score'


(a) 2.233333333333333

(b)0.9777777777777777

(c) 0.899999999999999

(d) -2.23333333333333

**Option b**

In [ ]:
import numpy as np
import pandas as pd
from sklearn import svm, datasets
iris = datasets.load_iris()
from sklearn.model_selection import train_test_split
#np.random.seed(42)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.3,random_state=42)
def COMPUTE_SCORE(X_train, y_train, X_test, y_test):
  model1 = svm.LinearSVC(penalty='l2', loss='hinge')
  model1.fit(X_train,y_train)
  score1=model1.score(X_test, y_test)
  return score1
score1 =COMPUTE_SCORE(X_train, y_train, X_test, y_test)
print(score1) 

0.9777777777777777


/usr/local/lib/python3.7/dist-packages/sklearn/svm/_base.py:1208: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  ConvergenceWarning,


#Question 5

Write a function `hyperparameter_search`which accepts the Kernel and regularization parameter as inputs and returns the `avg_score`of the models with the below mentioned hyperparameters. 
- Split the Iris dataset into train and test set with 70:30 ratio 
- kernels = `['linear', 'rbf']`
- Regularization `C = [5, 10,100]`
- Cross Validation = 10
-`random_state=42`

Which of the following options give the `accuracy_score` for the `iris dataset`?

(a) -1

(b) -2

(c) 1

(d) 0.8

**Option C**


In [ ]:
import numpy as np
import pandas as pd
import json
import random
from sklearn import svm, datasets
from sklearn.model_selection import cross_val_score
iris = datasets.load_iris()
from sklearn.model_selection import train_test_split
np.random.seed(42)
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.3,random_state=42)



In [ ]:

kernels = ['linear', 'rbf']
C = [5, 10,100]

def hyperparamater_search(kernels, C):

#Your code starts here
  
  avg_score = []
  for i in kernels:
    for j in C:
      scores = cross_val_score(svm.SVC(kernel=i,C=j,gamma='auto'),iris.data, iris.target, cv=10)
      #avg_score[i + '_' + str(j)] = np.average(scores)
      avg_score.append(scores)
  avg_score=np.array(avg_score)   
  return np.max(avg_score)
  #return avg_score
student_code = hyperparamater_search(kernels, C)
print(student_code)


1.0


#Graded Questions

#Question 1

Write a function `compute_GridSearchCV` which accepts the Kernel and regularization parameters as inputs and returns the Mean cross-validated score of the best_estimator, denoted with `best_score_` of the models with the below mentioned hyperparameters:
- Split the Iris dataset into train and test set with 70:30 ratio 
- Import svm.SVC as 'model'
- kernels = ['linear' , 'rbf']
- Regularization = [1,15,25]
- gamma = 'auto'
- Cross Validation = 4
- `random_state=0`

(a) 0.9799075391180654

(b) 0.8182475236540654

(c) 0.7999999995540654

(d) 0.1111111122223444


**(Option a)**

In [ ]:
import numpy as np
import pandas as pd
from sklearn import svm, datasets
iris = datasets.load_iris()
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.3,random_state = 0)

In [ ]:
import json
import random

np.random.seed(42)

#generating code space

# evaluating code space 
def COMPUTE_GridSearchCV(kernels, C):
    from sklearn.model_selection import GridSearchCV
    clf = GridSearchCV(svm.SVC(gamma='auto'), {
    'C': [1,15,25],
    'kernel': ['linear','rbf']
    }, cv=4, return_train_score=False)
    clf.fit(iris.data, iris.target)
    return clf.best_score_

In [ ]:
kernels = ['linear', 'rbf']
C = [1,15,25]
actual_code = COMPUTE_GridSearchCV(kernels, C)
print(actual_code)

0.9799075391180654


# Question 2 and 3

**Read the instructions given below to answer the two questions given below.**

Split the `Social_Network_Ads` dataset (https://drive.google.com/file/d/1qUa1GlG4X4ZY_4E0e7jPR-z7AG7NIDbE/view?usp=sharing) into training and test set in 75:25 ratio.
- Fit and transform the train and test set of the feature matrix by applying `StandardScaler` transformer.
- Fit a linear SVM (with `random_state = 0`and `linear` kernel) to training data. 

**Question 2**

The predicted data returns an `accuracy_score` on test data. Which of the following option represents the calculated `accuracy_score`?

(a) 0.88

(b) 0.99

(c) 0.77

(d)1.20

**Option a**

**Question 3**

Calculate the confusion matrix obtained  from the above predicted data.

(a) [[5  63]
 [ 7 25]]

(b) [[63  5]
 [ 7 25]]

(c) [[63  5]
 [ 25 7]]

(d) [[5  63]
 [ 25 7]]

**Option b**

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
np.random.seed(42)

In [ ]:
dataset = pd.read_csv('Social_Network_Ads.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

In [ ]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'linear', random_state = 0)
classifier.fit(X_train, y_train)

SVC(kernel='linear', random_state=0)

In [ ]:
y_pred = classifier.predict(X_test)
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[63  5]
 [ 7 25]]


0.88

#Multiclass classification

#Questions 4 and 5

**Question 4**

From the MNIST dataset, consider the first 20,000 data samples as training data and the next 5,000 data samples as test data. Fit a pipeline with MinMaxScaler and a classifier with SVC, linear kernel, one vs rest decision_function_shape and `class_weight=None` to this dataset and answer the following questions.

**What is the sum of the main diagonal elements of the confusion matrix?**

(a) 4523

(b) 4423

(c) 4623

(d) 4693

**Option c**

**Question 5**

Which of the following are the correct values of precision, recall and f1_Score?

(a) Precision: 0.90 
Recall: 0.89 
f1_Score: 0.90 

(b) Precision: 0.99 
Recall: 0.99 
f1_Score: 0.99 

(c) Precision: 0.92 
Recall: 0.92 
f1_Score: 0.92 

(d) Precision: 0.14 
Recall: 0.14 
f1_Score: 0.14 

**Option c**

In [ ]:
# Common imports
import numpy as np
import os
import io
import warnings

#sklearn specific imports
from sklearn.datasets import fetch_openml
from sklearn.preprocessing import MinMaxScaler,StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.dummy import DummyClassifier
from sklearn.linear_model import Perceptron
from sklearn.metrics import hinge_loss
from sklearn.metrics import ConfusionMatrixDisplay, confusion_matrix, precision_recall_curve
from sklearn.metrics import precision_score, recall_score, classification_report
from sklearn.metrics import make_scorer
from sklearn.model_selection import cross_validate, cross_val_predict,GridSearchCV
from pprint import pprint

# To plot pretty figures
%matplotlib inline
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns
# Import the libraries for performing classification
from sklearn import svm
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
from sklearn.metrics import classification_report
from sklearn.metrics import plot_roc_curve
from sklearn.metrics import roc_auc_score
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.pipeline import Pipeline
from sklearn import metrics
from sklearn.metrics import plot_confusion_matrix
from sklearn.model_selection import cross_val_score
#global matplotlib settings
mpl.rc('figure',figsize=(8,6))
mpl.rc('axes', labelsize=14)
mpl.rc('xtick', labelsize=12)
mpl.rc('ytick', labelsize=12)

# to make this notebook's output stable across runs
np.random.seed(42)

In [ ]:
X,y= fetch_openml('mnist_784',version=1,return_X_y=True) 
#it returns Data and label as a pandas dataframe
X = X.to_numpy()
y = y.to_numpy()

X_train = X[0:20000,:]
X_test = X[20000:25000,:]
y_train = y[0:20000]
y_test = y[20000:25000]

print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(20000, 784) (5000, 784) (20000,) (5000,)


In [ ]:
# Create a pipeline

pipe_2 = Pipeline([('scaler', MinMaxScaler()),
                         ("classifier", svm.SVC(kernel='linear', decision_function_shape='ovr', C=1, class_weight=None))])

# Fit the estimator , pipeline

pipe_2.fit(X_train,y_train)

# Get the predictions

y_pred = pipe_2.predict(X_test)

cm = confusion_matrix(y_test, y_pred)
print('Confusion matrix : \n', cm)
out = np.sum(np.diag(cm))
out

Confusion matrix : 
 [[469   0   1   0   0   5   1   1   1   0]
 [  1 555   2   4   0   1   1   1   3   0]
 [  5   4 479   6   9   1   3   6   7   1]
 [  3   3  13 462   0  19   0   3   9   4]
 [  2   0   6   0 468   1   2   4   1  16]
 [ 14   0   0  18   2 405   3   2   7   9]
 [  1   2   2   0   6   9 471   0   0   0]
 [  0   2   4   1   7   1   0 483   0   6]
 [  3  10  11  15   0  19   6   3 396   3]
 [  3   6   1   2  21   0   0  26   2 435]]


4623

In [ ]:
print(cm.shape)

(10, 10)


In [ ]:
from sklearn.metrics import precision_score, recall_score, f1_score

precisionScore = precision_score(y_test, y_pred, average='micro')
recallSscore = recall_score(y_test, y_pred, average='micro')
f1Score = f1_score(y_test, y_pred, average='micro')

print("Precision: {:.2f} %".format(precisionScore))
print("Recall: {:.2f} %".format(recallSscore))
print("f1_Score: {:.2f} %".format(f1Score))

Precision: 0.92 %
Recall: 0.92 %
f1_Score: 0.92 %


# Question 6

Consider the MNIST dataset, split it into training and test set in 50:50 ratio with `random_state = 42`. Fit a SVM model using pipeline with StandardScalar, SVM classifier `kernel='poly'` and `degree = 3`,  `decision_function_shape='ovr'`and `class_weight='balanced'`, `C=10`. Train the model on training data, and make predictions for test data. Generate the Classification report and choose the correct value for weighted avg of f1_score.

(a) 0.96

(b) 0.97

(c) 0.98

(d) 0.99

**Option b**


In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.5, random_state = 45)
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(35000, 784) (35000, 784) (35000,) (35000,)


In [ ]:
pipe_1 = Pipeline([('scaler', StandardScaler()),
                         ("classifier", SVC(kernel='poly', degree = 3, decision_function_shape='ovr', class_weight='balanced', C=10))])
pipe_1.fit(X_train,y_train)

Pipeline(steps=[('scaler', StandardScaler()),
                ('classifier',
                 SVC(C=10, class_weight='balanced', kernel='poly'))])

In [ ]:
y_pred = pipe_1.predict(X_test)

CR = classification_report(y_test, y_pred)
print('Classification report \n')
print(CR)

Classification report 

              precision    recall  f1-score   support

           0       0.99      0.99      0.99      3415
           1       0.99      0.99      0.99      3854
           2       0.97      0.97      0.97      3484
           3       0.97      0.96      0.97      3550
           4       0.97      0.98      0.97      3450
           5       0.97      0.97      0.97      3133
           6       0.99      0.98      0.98      3494
           7       0.98      0.96      0.97      3692
           8       0.95      0.97      0.96      3429
           9       0.96      0.96      0.96      3499

    accuracy                           0.97     35000
   macro avg       0.97      0.97      0.97     35000
weighted avg       0.97      0.97      0.97     35000



#Question 7
Write the function `compute_score(X_train, y_train, X_test, y_test)` to do the following on the `Iris` dataset-

Write your code keeping in mind:
- Split the Iris dataset into train and test set with 70:30 ratio 
- Import svm.SVC as 'model'
- kernel as 'poly', regularization parameter as 10 and gamma as 'auto'
- Train the 'model' and mark the computed 'score'


(a) 2.0

(b) 1.0

(c) -1.0

(d) -2.0

**Option b**


In [ ]:
import numpy as np
from sklearn import svm, datasets
import json
import random
np.random.seed(42)
iris = datasets.load_iris()
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.3,random_state = 42)
def COMPUTE_SCORE(X_train, y_train, X_test, y_test):
  model1 = svm.SVC(kernel='poly',C=10,gamma='auto')
  model1.fit(X_train,y_train)
  score1=model1.score(X_test, y_test)
  return score1
score1 =COMPUTE_SCORE(X_train, y_train, X_test, y_test)
print(score1) 

1.0


#Question 8

Write the function `compute_score(X_train, y_train, X_test, y_test)` to do the following on the `Iris` dataset-

Write your code keeping in mind:
- Split the Iris dataset into train and test set with 70:30 ratio 
- Import svm.SVC as 'model'
- kernel as 'sigmoid', regularization parameter as 25 and gamma as 'auto'
- Train the 'model' and mark the computed 'score'


(a) 0.2666666666666666

(b) 0.9555555555555556

(c) 1.8122222222222222

(d) 2.2111111111111111

**Option a**


In [ ]:
#Arat
import numpy as np
import pandas as pd
from sklearn import svm, datasets
iris = datasets.load_iris()
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.3)
def COMPUTE_SCORE(X_train, y_train, X_test, y_test):
  model1 = svm.SVC(kernel='sigmoid',C=25,gamma='auto')
  model1.fit(X_train,y_train)
  score1=model1.score(X_test, y_test)
  return score1
score1 =COMPUTE_SCORE(X_train, y_train, X_test, y_test)
print(score1)

0.28888888888888886


#Question 9

Import the `iris` dataset and drop the rows where `class=Iris-setosa`. Apply a pipeline containing a `MinMaxScaler()`function called`Scaler` and a `svm.svc()` called `classifier`. Split the `iris` dataset into 75:25 ratio with `random_state=0`. Mark the correct precision score.

(a) 0.00

(b) 1.22

(C) 0.96

(d) 2.33

**Option c**



In [ ]:
# Import the libraries for performing classification
from sklearn import svm
from sklearn.svm import LinearSVC
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
from sklearn.metrics import classification_report
from sklearn.metrics import plot_roc_curve
from sklearn.metrics import roc_auc_score
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.pipeline import Pipeline
from sklearn import metrics
from sklearn.metrics import plot_confusion_matrix
from sklearn.model_selection import cross_val_score

In [ ]:
#Define the column names
col_name=["sepal_length_in_cm", "sepal_width_in_cm","petal_length_in_cm","petal_width_in_cm", "class"]

#Read the dataset
df = pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data", header = None, names= col_name)

In [ ]:
data = df
# get names of indexes for which column 'class' has value 'Iris-setosa'
index_names = data[ data["class"] == 'Iris-setosa' ].index
  
# drop these row indexes
# from dataFrame
data.drop(index_names, inplace = True)
  
data

sepal_length_in_cm  sepal_width_in_cm  ...  petal_width_in_cm            class
50                  7.0                3.2  ...                1.4  Iris-versicolor
51                  6.4                3.2  ...                1.5  Iris-versicolor
52                  6.9                3.1  ...                1.5  Iris-versicolor
53                  5.5                2.3  ...                1.3  Iris-versicolor
54                  6.5                2.8  ...                1.5  Iris-versicolor
..                  ...                ...  ...                ...              ...
145                 6.7                3.0  ...                2.3   Iris-virginica
146                 6.3                2.5  ...                1.9   Iris-virginica
147                 6.5                3.0  ...                2.0   Iris-virginica
148                 6.2                3.4  ...                2.3   Iris-virginica
149                 5.9                3.0  ...                1.8   Iris-virginica

[100 rows x 5 columns]

In [ ]:
# Separatre the input and output feature values

X = data.iloc[:,:-1]
y = data.iloc[:,-1].values

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

print('Shape of training data',X_train.shape)
print('Shape of training labels', y_train.shape)
print('Shape of testing data', X_test.shape)
print('Shape of testing labels',y_test.shape)

Shape of training data (75, 4)
Shape of training labels (75,)
Shape of testing data (25, 4)
Shape of testing labels (25,)


In [ ]:
X=np.array(X_train)
y=np.array(y_train)
# Let us consider sepal length and sepal width
X=X[:,(0,1)]
X.shape

(75, 2)

In [ ]:
# Create a pipeline

pipe_2 = Pipeline([('scaler', MinMaxScaler()),
                         ("classifier", svm.SVC(kernel='linear', decision_function_shape='ovr', C=1, class_weight=None))])

# Fit the estimator , pipeline

pipe_2.fit(X_train,y_train)

# Get the predictions

y_pred = pipe_2.predict(X_test)

In [ ]:
from sklearn.metrics import precision_score, recall_score, f1_score

precisionScore = precision_score(y_test, y_pred, average='micro')
recallSscore = recall_score(y_test, y_pred, average='micro')
f1Score = f1_score(y_test, y_pred, average='micro')

print("Precision: {:.2f} ".format(precisionScore))
print("Recall: {:.2f} ".format(recallSscore))
print("f1_Score: {:.2f} ".format(f1Score))

Precision: 0.96 
Recall: 0.96 
f1_Score: 0.96 
